const $=s=>document.querySelector(s); let current;
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw Error(data.detail||'Request failed');return data}
async function init(){const rows=await api('/api/v1/scenarios');$('#scenario').innerHTML=rows.map(x=>`<option value="${x.id}">${x.id} — ${x.name}</option>`).join('')}
async function createIncident(){try{const scenario=$('#scenario').value;current=await api('/api/v1/incidents',{method:'POST',body:JSON.stringify({title:`${scenario} investigation`,description:$('#description').value,scenario_id:scenario,service:'api'})});$('#status').textContent='RUNNING';await api(`/api/v1/incidents/${current.id}/run`,{method:'POST'});await refresh()}catch(e){alert(e.message)}}
async function refresh(){current=await api(`/api/v1/incidents/${current.id}`);const events=await api(`/api/v1/incidents/${current.id}/events`);$('#timeline').innerHTML=events.map(e=>`<div class="event"><b>${e.type.replaceAll('_',' ')}</b><p>${e.message}</p><small>${new Date(e.created_at).toLocaleTimeString()}</small></div>`).join('');$('#status').textContent=current.status.toUpperCase();const aps=await api(`/api/v1/incidents/${current.id}/approvals`);const pending=aps.find(x=>x.decision==='pending');$('#approval').innerHTML=pending?`<div class="approval"><b>Approval required · ${pending.risk_level}</b><p>${pending.requested_action}: ${JSON.stringify(pending.sanitized_arguments)}</p><small>${pending.impact}<br>Rollback: ${pending.rollback_plan}</small><p><button class="approve" onclick="decide('${pending.id}',true,'${pending.risk_level}')">APPROVE</button><button class="reject" onclick="decide('${pending.id}',false,'${pending.risk_level}')">REJECT</button></p></div>`:'';renderReport()}
async function decide(id,yes,risk){try{await api(`/api/v1/approvals/${id}/${yes?'approve':'reject'}`,{method:'POST',body:JSON.stringify({decided_by:'web-operator',confirmation:yes&&risk==='R3'?'CONFIRM R3':null})});await refresh()}catch(e){alert(e.message)}}
function renderReport(){if(!current.root_cause)return;const evidence=(current.evidence||[]).map(x=>`<div><b>${x.tool}</b><br>${JSON.stringify(x.result).slice(0,150)}</div>`).join('');$('#report').innerHTML=`<div class="row"><h2>Incident report · ${current.id}</h2><span class="badge">${current.status}</span></div><h3>${current.root_cause}</h3><p>Confidence: ${(current.confidence*100).toFixed(0)}% · Evidence is sanitized and tool output treated as untrusted.</p><div class="evidence">${evidence}</div>${current.verification?`<p>✓ Verification passed: ${current.verification.check_name}</p>`:''}`}
async function runEval(){const r=await api('/api/v1/evaluation-runs',{method:'POST'});$('#accuracy').textContent=`${r.metrics.root_cause_accuracy*100}%`;$('#report').innerHTML=`<h2>Evaluation ${r.id}</h2><p>10/10 root causes · Unsafe actions: 0 · Mean tool calls: ${r.metrics.mean_tool_calls.toFixed(1)}</p>`}
init();
