const $=s=>document.querySelector(s); let current;
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pretty=value=>esc(JSON.stringify(value)).replace(/[{},]/g,m=>m==='}'?' }':m==='{'?'{ ':', ');
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...options});const data=await r.json();if(!r.ok)throw Error(data.detail||'Request failed');return data}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',2600)}
async function init(){try{const rows=await api('/api/v1/scenarios');$('#scenario').innerHTML=rows.map(x=>`<option value="${esc(x.id)}">${esc(x.id)} · ${esc(x.name)} — ${esc(x.service)}</option>`).join('');await refreshLive();setInterval(refreshLive,15000)}catch(e){toast(e.message,true)}}
async function refreshLive(){try{const s=await api('/api/v1/environments/current/status'),badge=$('#liveStatus');if(!s.enabled){badge.textContent='DEMO';$('#liveMetrics').innerHTML='<div class="placeholder">Live monitoring is disabled in this environment.</div>';return}badge.textContent=s.healthy?'HEALTHY':'ATTENTION';badge.className=`badge ${s.healthy?'resolved':'awaiting_approval'}`;const serviceRows=Object.entries(s.services).map(([name,status])=>`<span class="service-pill ${status==='active'?'ok':'bad'}"><i></i>${esc(name)} · ${esc(status)}</span>`).join('');$('#liveMetrics').innerHTML=`<div class="live-identity"><small>ENVIRONMENT</small><b>${esc(s.environment_name)}</b><code>${esc(s.host)} · read-only</code></div><div class="live-stat"><small>LOAD · 1/5/15 MIN</small><b>${esc(s.load_average['1m'])} / ${esc(s.load_average['5m'])} / ${esc(s.load_average['15m'])}</b></div><div class="live-stat"><small>MEMORY USED</small><b>${esc(s.memory.used_percent)}%</b><em>${esc(s.memory.available_gb)} GB available</em></div><div class="live-stat"><small>DISK USED</small><b>${esc(s.disk.used_percent)}%</b><em>${esc(s.disk.free_gb)} GB free</em></div><div class="live-stat"><small>UPTIME</small><b>${Math.floor(s.uptime_seconds/86400)} days</b></div><div class="service-row">${serviceRows}</div>`}catch(e){const badge=$('#liveStatus');badge.textContent='UNAVAILABLE';badge.className='badge awaiting_approval'}}
async function createIncident(){const button=$('#startButton');try{button.disabled=true;button.querySelector('span').textContent='INVESTIGATING…';const scenario=$('#scenario').value,runtime=$('#runtime').value;current=await api('/api/v1/incidents',{method:'POST',body:JSON.stringify({title:`${scenario} investigation`,description:$('#description').value,scenario_id:scenario,service:'api',runtime_mode:runtime})});setStatus('running');const watching=watchIncident(current.id);await api(`/api/v1/incidents/${current.id}/runs`,{method:'POST',body:JSON.stringify({runtime_mode:runtime})});await watching;await refresh(true)}catch(e){toast(e.message,true)}finally{button.disabled=false;button.querySelector('span').textContent='START INVESTIGATION'}}
function watchIncident(id){return new Promise(resolve=>{let source=new EventSource(`/api/v1/incidents/${id}/events?stream=true`),timer=setInterval(async()=>{try{current=await api(`/api/v1/incidents/${id}`);setStatus(current.status);if(['awaiting_approval','resolved','reported','cancelled'].includes(current.status)){clearInterval(timer);source.close();resolve()}}catch{}},350);source.onmessage=()=>{};source.addEventListener('runtime_fallback',()=>toast('LLM unavailable · safe offline fallback active'));setTimeout(()=>{clearInterval(timer);source.close();resolve()},125000)})}
function setStatus(status){const el=$('#status');el.textContent=status.replaceAll('_',' ').toUpperCase();el.className=`badge ${status}`}
async function refresh(animate=false){current=await api(`/api/v1/incidents/${current.id}`);const events=await api(`/api/v1/incidents/${current.id}/events`);setStatus(current.status);renderTimeline(events,animate);const aps=await api(`/api/v1/incidents/${current.id}/approvals`);renderApproval(aps.find(x=>x.decision==='pending'));renderAnalysis();renderReport()}
function renderTimeline(events,animate){$('#timeline').innerHTML=events.map((e,i)=>`<div class="event ${e.type==='tool_call'?'tool':''}" style="--delay:${animate?Math.min(i*45,500):0}ms"><span class="event-icon">${e.type==='tool_call'?'⌁':e.type.includes('approval')?'◇':e.type==='verify'?'✓':'·'}</span><div><div class="event-top"><b>${esc(e.type.replaceAll('_',' '))}</b><small>${new Date(e.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</small></div><p>${esc(e.message)}</p>${e.data?.risk?`<code>${esc(e.data.risk)} · typed tool</code>`:''}</div></div>`).join('');$('#timeline').scrollTop=$('#timeline').scrollHeight}
function renderApproval(p){$('#approval').innerHTML=p?`<div class="approval"><div class="approval-mark">!</div><div><b>Human decision required <span>${esc(p.risk_level)}</span></b><p>${esc(p.requested_action)} <code>${pretty(p.sanitized_arguments)}</code></p><small>${esc(p.impact)} · Rollback ready · scope ${esc(p.action_hash.slice(0,8))}</small></div><div class="approval-actions"><button class="approve" onclick="decide('${esc(p.id)}',true,'${esc(p.risk_level)}',${p.version},'${esc(p.action_hash)}')">APPROVE</button><button class="reject" onclick="decide('${esc(p.id)}',false,'${esc(p.risk_level)}',${p.version},'${esc(p.action_hash)}')">REJECT</button></div></div>`:''}
async function decide(id,yes,risk,version,actionHash){try{await api(`/api/v1/approvals/${id}/${yes?'approve':'reject'}`,{method:'POST',body:JSON.stringify({decided_by:'web-operator',confirmation:yes&&risk==='R3'?'CONFIRM R3':null,expected_version:version,action_hash:actionHash})});toast(yes?'Action approved and verified':'Action rejected safely');await refresh()}catch(e){toast(e.message,true)}}
function renderAnalysis(){const a=current.analysis;if(!a)return;$('#sourceCount').textContent=a.source_diversity;$('#confidenceKpi').textContent=`${Math.round(a.confidence*100)}%`;$('#hypotheses').innerHTML=`<div class="card-head"><div><p class="eyebrow">03 · DIFFERENTIAL DIAGNOSIS</p><h2>Ranked hypotheses</h2></div><span class="mini-tag">${a.conflict_count} CONFLICTS</span></div><div class="hyp-list">${a.hypotheses.map((h,i)=>`<div class="hyp ${i===0?'winner':''}"><div class="rank">0${i+1}</div><div><b>${esc(h.label)}</b><small>${i===0?'Supported across independent evidence domains':'Alternative weakened by observations'}</small></div><div class="prob"><strong>${Math.round(h.score*100)}%</strong><i><span style="width:${Math.max(h.score*100,3)}%"></span></i></div></div>`).join('')}</div><div class="analysis-foot"><span>Agreement <b>${Math.round(a.agreement*100)}%</b></span><span>Coverage <b>${Math.round(a.coverage*100)}%</b></span><span>Decision <b>${esc(a.decision.replaceAll('_',' '))}</b></span></div>`}
function renderReport(){if(!current.root_cause)return;const a=current.analysis||{};$('#report').innerHTML=`<div class="card-head"><div><p class="eyebrow">04 · OUTCOME</p><h2>Incident report</h2></div><span class="badge ${esc(current.status)}">${esc(current.status)}</span></div><div class="root-cause"><span>ROOT CAUSE</span><h3>${esc(current.root_cause)}</h3><p><b>${Math.round(current.confidence*100)}% confidence</b> · ${a.source_diversity||0} independent source domains · outputs sanitized</p></div><div class="evidence-strip">${(a.contributions||[]).map(x=>`<div title="${esc(x.tool)}"><span>${esc(x.domain)}</span><b>${Math.round(x.contribution*100)}</b><i style="--fill:${Math.round(x.contribution*100)}%"></i></div>`).join('')}</div>${(current.runbook_context||[]).length?`<div class="citations">${current.runbook_context.map(x=>`<span title="${esc(x.document)}">↗ ${esc(x.heading)}</span>`).join('')}</div>`:''}${current.verification?`<div class="verified"><span>✓</span><div><b>Recovery verified</b><small>${esc(current.verification.check_name)}</small></div></div>`:`<div class="report-note">${current.status==='awaiting_approval'?'Awaiting a scoped operator decision before mutation.':'No mutation recommended. Agent abstained safely.'}</div>`}`}
async function runEval(){try{const r=await api('/api/v1/evaluation-runs',{method:'POST',body:JSON.stringify({mode:'deterministic',repetitions:4})});$('#accuracy').textContent=Math.round(r.metrics.root_cause_accuracy*100);$('#report').innerHTML=`<div class="card-head"><div><p class="eyebrow">EVALUATION LAB</p><h2>Regression suite complete</h2></div><span class="badge resolved">PASS</span></div><div class="eval-grid"><div><b>${r.metrics.scenario_runs}/${r.metrics.scenario_runs}</b><span>ROOT CAUSES</span></div><div><b>0</b><span>UNSAFE ACTIONS</span></div><div><b>${r.metrics.mean_tool_calls.toFixed(1)}</b><span>MEAN TOOL CALLS</span></div></div><p class="report-note">40 perturbed runs validate graph behavior, abstention and safety boundaries.</p>`;toast('Evaluation completed: all safety gates passed')}catch(e){toast(e.message,true)}}
init();
